# Основные параметры
folder_path: "/home/nikola/Desktop/narek/new_proj/PocketMaster/data/family_set_2025/files/A9JQL9"
save_dir: "/home/nikola/Desktop/narek/new_proj/PocketMaster/data/family_set_2025/files/A9JQL9/yohoool"

# Очистка
do_preprocess: "1"    # Провести предварительную очистку структур? (1 - да, 0 - нет)
clean_options: ["1"]  # Пожалуйста, выберите подходящие опции предварительной обработки структур, например: ["1, 2, 3"]
                      # 1 — Удалить воду (solvent)
                      # 2 — Удалить ионы металлов (metal ions)
                      # 3 — Удалить всё, кроме белка (оставить только полимерную цепь)
                      # 4 — Удалить альтернативные конформации (altloc)
                      # 5 — Удалить атомы водорода (H)
                      # 6 — Удалить анизотропные параметры (ANISOU)
                      # 7 — Не очищать / Завершить выбор
                      # 8 - Сохранить обработанные структуры в определённой папке"

# Референсы
ref_pocket: "pdb3acw" # Выберите референсную структуру для определения кармана, например: "pdb3acw"
ref_align: "pdb2zco"  # Выберите референсную структуру для выравнивания, например: "pdb2zco"

# Метод кармана
pocket_method: 1      # Выбери способ задания кармана:
                      # 1 - Радиальное ( ввести остаток ID и радиус в Å)
                      # 2 - Вручную (ввести список остатков)
                      # 3 - По всей цепи (указать chain ID)
                      # 4 - По всем HET-группам во всех структурах (в заданном радиусе Å)

ligand_resi: "1001"   # Введи номер остатка, например: '400'
ligand_chain: "A"     # Введи chain ID, например: 'A'
radius: 7.0           # Введи радиус для кармана в Å, например: 7 (по умолчанию 7)
resi_chain: "PRO 46 A, ASN 61 A" # Введи список остатков в формате (resn resi chain), например: PRO 46 A, ASN 61 A
chain_id: "A"         # Введи идентификатор цепи (chain ID), например: A

# Сравнение и RMSD
comparison_mode: 1    # Выбери режим сравнения:
                      # 1 - Все со всеми (all vs all)
                      # 2 - Все с референсом (all vs ref) 
rmsd_method: 2        # Выбери метод расчёта RMSD:
                      # 1 - align   (Строгая оценка, исключает несоответствия)
                      # 2 - super   (Гибкий подход, учитывает несовпадения)
                      # 3 - rms     (Точное RMSD, требует полное соответствие атомов)
                      # 4 - rms_cur (Быстрее, приближённое RMSD, тоже требует полное соответствие)

# Кластеризация
linkage_method: 2     # Выбери метод иерархической кластеризации:
                      # 1 - ward (минимизация внутрикластерной дисперсии, требует евклидово расстояние)
                      # 2 - single (минимальное расстояние между кластерами)
                      # 3 - complete (максимальное расстояние между кластерами)
                      # 4 - average (среднее расстояние между кластерами (UPGMA))
                      # 5 - centroid (расстояние между центрами масс кластеров)
                      # 6 - median (медианное расстояние между кластерами)
                      # 7 - weighted (взвешенное среднее расстояние (WPGMA))

cl_choice: 3          # Выберите способ кластеризации:
                      # 1 — Задать количество кластеров (maxclust)
                      # 2 — Задать порог расстояния (distance)
                      # 3 — Автоматический выбор числа кластеров (альтернативный вариант)
num_clusters: 3       # Введите желаемое количество кластеров, например: 3
distance_threshold: 2 # Введите порог расстояния, например: 2

#    | Метод        | Компактные кластеры | Вытянутые кластеры | Чувствительность к выбросам |
#    | ------------ | ------------------- | ------------------ | --------------------------- |
#    | 1. ward      | ✅ отлично          | ❌ плохо          | ⚠️ средняя                  |
#    | 2. single    | ❌ плохо            | ✅ отлично        | ⚠️ высокая                  |
#    | 3. complete  | ✅ хорошо           | ❌ плохо          | ✅ устойчив                 |
#    | 4. average   | ✅ универсально     | ✅ неплохо        | ⚠️ средняя                  |
#    | 5. centroid  | ⚠️ нестабильно      | ⚠️ нестабильно    | ⚠️ нестабильно              |
#    | 6. median    | ⚠️ нестабильно      | ⚠️ нестабильно    | ⚠️ нестабильно              |
#    | 7. weighted  | ✅ хорошо           | ✅ хорошо         | ⚠️ средняя                  |
